version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    # dockerfile: dockerfile.multistage
    container_name: api_gateway1
    ports:
      - 7777:7777
    depends_on:
      - lrc_service
      - tweets_service
      - user_service
    networks:
      - mynetwork

  user_service:
    build: ./user
    # dockerfile: dockerfile.multistage
    container_name: user_service_container
    image: user_service_image
    environment:
      - PG_URL=postgres://postgres:2005@user_postgres:5432/udevs?sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      - user_postgres
      - redis
    networks:
      - mynetwork

  tweets_service:
    build: ./tweets
    # dockerfile: dockerfile.multistage
    container_name: tweets_service_container
    image: tweets_service_image
    environment:
      - PG_URL=postgres://postgres:2005@udevs1:5432/udevs1?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      - tweets_postgres
    networks:
      - mynetwork

  lrc_service:
    build: ./like_retweet
    # dockerfile: dockerfile.multistage
    container_name: lrc_service_container
    image: like_retweet_service_image
    environment:
      - PG_URL=postgres://postgres:2005@booking_postgres:5432/udevs2?sslmode=disable
    ports:
      - 8082:8082
    depends_on:
      - lrc_postgres
    networks:
      - mynetwork

  notification_service:
    build: ./notification_service
    container_name: notification_service_container
    image: notification_service_image
    # dockerfile: dockerfile.multistage
    ports:
      - "8083:8083"
      - "50051:50051"
    depends_on:
      - broker
    networks:
      - mynetwork

  broker:
    image: apache/kafka:latest
    container_name: kafka_broker
    ports:
      - "9092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - mynetwork

  user_postgres:
    image: postgres:14-alpine
    container_name: user_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: udevs
      PGDATA: /var/lib/postgresql/data
    volumes:
      - user-db-data:/var/lib/postgresql/data
      - ./user/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d udevs || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  migrate_user:
    image: migrate/migrate
    volumes:
      - ./user/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:2005@user_postgres:5432/udevs?sslmode=disable", "up"]
    depends_on:
      user_postgres:
        condition: service_healthy
    networks:
      - mynetwork

  tweets_postgres:
    image: postgres:14-alpine
    container_name: tweets_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: udevs1
      PGDATA: /var/lib/postgresql/data
    volumes:
      - tweets-db-data:/var/lib/postgresql/data
      - ./tweets/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d udevs1 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  migrate_tweets:
    image: migrate/migrate
    volumes:
      - ./tweets/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:2005@tweets_postgres:5432/udevs1?sslmode=disable", "up"]
    depends_on:
      tweets_postgres:
        condition: service_healthy
    networks:
      - mynetwork

  lrc_postgres:
    image: postgres:14-alpine
    container_name: lrc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: udevs2
      PGDATA: /var/lib/postgresql/data
    volumes:
      - like_retweet-db-data:/var/lib/postgresql/data
      - ./like_retweet/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d udevs2 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  migrate_lrc:
    image: migrate/migrate
    volumes:
      - ./like_retweet/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:2005@lrc_postgres:5432/udevs2?sslmode=disable", "up"]
    depends_on:
      lrc_postgres:
        condition: service_healthy
    networks:
      - mynetwork

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6378:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  user-db-data:
  tweets-db-data:
  like_retweet-db-data: