// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/protos/tweets/tweets.proto

package tweets17

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tweets_CreateTweet_FullMethodName = "/Tweets/CreateTweet"
	Tweets_GetTweet1_FullMethodName   = "/Tweets/GetTweet1"
	Tweets_Update_FullMethodName      = "/Tweets/Update"
	Tweets_Delete_FullMethodName      = "/Tweets/Delete"
	Tweets_GetAllTweet_FullMethodName = "/Tweets/GetAllTweet"
)

// TweetsClient is the client API for Tweets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetsClient interface {
	CreateTweet(ctx context.Context, in *CreateTweetRequest, opts ...grpc.CallOption) (*CreateTweetResponse, error)
	GetTweet1(ctx context.Context, in *GetTweet, opts ...grpc.CallOption) (*CreateTweetResponse, error)
	Update(ctx context.Context, in *UpdateTweet, opts ...grpc.CallOption) (*CreateTweetResponse, error)
	Delete(ctx context.Context, in *GetTweet, opts ...grpc.CallOption) (*Respond1, error)
	GetAllTweet(ctx context.Context, in *GetAlltweets, opts ...grpc.CallOption) (*GetAll, error)
}

type tweetsClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetsClient(cc grpc.ClientConnInterface) TweetsClient {
	return &tweetsClient{cc}
}

func (c *tweetsClient) CreateTweet(ctx context.Context, in *CreateTweetRequest, opts ...grpc.CallOption) (*CreateTweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTweetResponse)
	err := c.cc.Invoke(ctx, Tweets_CreateTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) GetTweet1(ctx context.Context, in *GetTweet, opts ...grpc.CallOption) (*CreateTweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTweetResponse)
	err := c.cc.Invoke(ctx, Tweets_GetTweet1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) Update(ctx context.Context, in *UpdateTweet, opts ...grpc.CallOption) (*CreateTweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTweetResponse)
	err := c.cc.Invoke(ctx, Tweets_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) Delete(ctx context.Context, in *GetTweet, opts ...grpc.CallOption) (*Respond1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond1)
	err := c.cc.Invoke(ctx, Tweets_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) GetAllTweet(ctx context.Context, in *GetAlltweets, opts ...grpc.CallOption) (*GetAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAll)
	err := c.cc.Invoke(ctx, Tweets_GetAllTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetsServer is the server API for Tweets service.
// All implementations must embed UnimplementedTweetsServer
// for forward compatibility.
type TweetsServer interface {
	CreateTweet(context.Context, *CreateTweetRequest) (*CreateTweetResponse, error)
	GetTweet1(context.Context, *GetTweet) (*CreateTweetResponse, error)
	Update(context.Context, *UpdateTweet) (*CreateTweetResponse, error)
	Delete(context.Context, *GetTweet) (*Respond1, error)
	GetAllTweet(context.Context, *GetAlltweets) (*GetAll, error)
	mustEmbedUnimplementedTweetsServer()
}

// UnimplementedTweetsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTweetsServer struct{}

func (UnimplementedTweetsServer) CreateTweet(context.Context, *CreateTweetRequest) (*CreateTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTweet not implemented")
}
func (UnimplementedTweetsServer) GetTweet1(context.Context, *GetTweet) (*CreateTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTweet1 not implemented")
}
func (UnimplementedTweetsServer) Update(context.Context, *UpdateTweet) (*CreateTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTweetsServer) Delete(context.Context, *GetTweet) (*Respond1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTweetsServer) GetAllTweet(context.Context, *GetAlltweets) (*GetAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTweet not implemented")
}
func (UnimplementedTweetsServer) mustEmbedUnimplementedTweetsServer() {}
func (UnimplementedTweetsServer) testEmbeddedByValue()                {}

// UnsafeTweetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetsServer will
// result in compilation errors.
type UnsafeTweetsServer interface {
	mustEmbedUnimplementedTweetsServer()
}

func RegisterTweetsServer(s grpc.ServiceRegistrar, srv TweetsServer) {
	// If the following call pancis, it indicates UnimplementedTweetsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tweets_ServiceDesc, srv)
}

func _Tweets_CreateTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).CreateTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_CreateTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).CreateTweet(ctx, req.(*CreateTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_GetTweet1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).GetTweet1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_GetTweet1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).GetTweet1(ctx, req.(*GetTweet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).Update(ctx, req.(*UpdateTweet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).Delete(ctx, req.(*GetTweet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_GetAllTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlltweets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).GetAllTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_GetAllTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).GetAllTweet(ctx, req.(*GetAlltweets))
	}
	return interceptor(ctx, in, info, handler)
}

// Tweets_ServiceDesc is the grpc.ServiceDesc for Tweets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tweets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tweets",
	HandlerType: (*TweetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTweet",
			Handler:    _Tweets_CreateTweet_Handler,
		},
		{
			MethodName: "GetTweet1",
			Handler:    _Tweets_GetTweet1_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Tweets_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Tweets_Delete_Handler,
		},
		{
			MethodName: "GetAllTweet",
			Handler:    _Tweets_GetAllTweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/protos/tweets/tweets.proto",
}
