// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: internal/protos/notification/notification.proto

package not17

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNotification) Reset() {
	*x = GetNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_notification_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotification) ProtoMessage() {}

func (x *GetNotification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_notification_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotification.ProtoReflect.Descriptor instead.
func (*GetNotification) Descriptor() ([]byte, []int) {
	return file_internal_protos_notification_notification_proto_rawDescGZIP(), []int{0}
}

type ProduceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProduceMessage) Reset() {
	*x = ProduceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_notification_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProduceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceMessage) ProtoMessage() {}

func (x *ProduceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_notification_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceMessage.ProtoReflect.Descriptor instead.
func (*ProduceMessage) Descriptor() ([]byte, []int) {
	return file_internal_protos_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProduceMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EMailSendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EMailSendResponse) Reset() {
	*x = EMailSendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_notification_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMailSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMailSendResponse) ProtoMessage() {}

func (x *EMailSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_notification_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMailSendResponse.ProtoReflect.Descriptor instead.
func (*EMailSendResponse) Descriptor() ([]byte, []int) {
	return file_internal_protos_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *EMailSendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_protos_notification_notification_proto protoreflect.FileDescriptor

var file_internal_protos_notification_notification_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x11,
	0x45, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x43, 0x0a, 0x0c, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0c, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x45,
	0x4d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x6e, 0x6f, 0x74, 0x31, 0x37, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_notification_notification_proto_rawDescOnce sync.Once
	file_internal_protos_notification_notification_proto_rawDescData = file_internal_protos_notification_notification_proto_rawDesc
)

func file_internal_protos_notification_notification_proto_rawDescGZIP() []byte {
	file_internal_protos_notification_notification_proto_rawDescOnce.Do(func() {
		file_internal_protos_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_notification_notification_proto_rawDescData)
	})
	return file_internal_protos_notification_notification_proto_rawDescData
}

var file_internal_protos_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_protos_notification_notification_proto_goTypes = []any{
	(*GetNotification)(nil),   // 0: GetNotification
	(*ProduceMessage)(nil),    // 1: ProduceMessage
	(*EMailSendResponse)(nil), // 2: EMailSendResponse
}
var file_internal_protos_notification_notification_proto_depIdxs = []int32{
	1, // 0: Notification.Notification:input_type -> ProduceMessage
	2, // 1: Notification.Notification:output_type -> EMailSendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protos_notification_notification_proto_init() }
func file_internal_protos_notification_notification_proto_init() {
	if File_internal_protos_notification_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_notification_notification_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_notification_notification_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProduceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_notification_notification_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EMailSendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_notification_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_notification_notification_proto_goTypes,
		DependencyIndexes: file_internal_protos_notification_notification_proto_depIdxs,
		MessageInfos:      file_internal_protos_notification_notification_proto_msgTypes,
	}.Build()
	File_internal_protos_notification_notification_proto = out.File
	file_internal_protos_notification_notification_proto_rawDesc = nil
	file_internal_protos_notification_notification_proto_goTypes = nil
	file_internal_protos_notification_notification_proto_depIdxs = nil
}
