// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/protos/user/user.proto

package user17

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_Signup_FullMethodName         = "/User/Signup"
	User_VErify_FullMethodName         = "/User/VErify"
	User_Signin_FullMethodName         = "/User/Signin"
	User_LogOut_FullMethodName         = "/User/LogOut"
	User_User_Profile_FullMethodName   = "/User/User_Profile"
	User_Update_Profile_FullMethodName = "/User/Update_Profile"
	User_Delete_Profile_FullMethodName = "/User/Delete_Profile"
	User_Follow_FullMethodName         = "/User/Follow"
	User_Get_Followers_FullMethodName  = "/User/Get_Followers"
	User_Get_Following_FullMethodName  = "/User/Get_Following"
	User_Search_FullMethodName         = "/User/Search"
	User_Unfollow_FullMethodName       = "/User/Unfollow"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	Signup(ctx context.Context, in *SignUp, opts ...grpc.CallOption) (*Respond, error)
	VErify(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Respond, error)
	Signin(ctx context.Context, in *SignIn, opts ...grpc.CallOption) (*Respond, error)
	LogOut(ctx context.Context, in *LogOutDelete, opts ...grpc.CallOption) (*Respond, error)
	User_Profile(ctx context.Context, in *GET_UserProfile_Request, opts ...grpc.CallOption) (*GET_UserProfile_Response, error)
	Update_Profile(ctx context.Context, in *PUTUserProfile, opts ...grpc.CallOption) (*GET_UserProfile_Response, error)
	Delete_Profile(ctx context.Context, in *LogOutDelete, opts ...grpc.CallOption) (*Respond, error)
	Follow(ctx context.Context, in *Following, opts ...grpc.CallOption) (*Respond, error)
	Get_Followers(ctx context.Context, in *Followers, opts ...grpc.CallOption) (*GetFollowers, error)
	Get_Following(ctx context.Context, in *Followers, opts ...grpc.CallOption) (*GetFollowing, error)
	Search(ctx context.Context, in *Following, opts ...grpc.CallOption) (*GET_UserProfile_Response, error)
	Unfollow(ctx context.Context, in *Following, opts ...grpc.CallOption) (*Respond, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) Signup(ctx context.Context, in *SignUp, opts ...grpc.CallOption) (*Respond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond)
	err := c.cc.Invoke(ctx, User_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) VErify(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Respond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond)
	err := c.cc.Invoke(ctx, User_VErify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Signin(ctx context.Context, in *SignIn, opts ...grpc.CallOption) (*Respond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond)
	err := c.cc.Invoke(ctx, User_Signin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) LogOut(ctx context.Context, in *LogOutDelete, opts ...grpc.CallOption) (*Respond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond)
	err := c.cc.Invoke(ctx, User_LogOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) User_Profile(ctx context.Context, in *GET_UserProfile_Request, opts ...grpc.CallOption) (*GET_UserProfile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GET_UserProfile_Response)
	err := c.cc.Invoke(ctx, User_User_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Update_Profile(ctx context.Context, in *PUTUserProfile, opts ...grpc.CallOption) (*GET_UserProfile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GET_UserProfile_Response)
	err := c.cc.Invoke(ctx, User_Update_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Delete_Profile(ctx context.Context, in *LogOutDelete, opts ...grpc.CallOption) (*Respond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond)
	err := c.cc.Invoke(ctx, User_Delete_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Follow(ctx context.Context, in *Following, opts ...grpc.CallOption) (*Respond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond)
	err := c.cc.Invoke(ctx, User_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Get_Followers(ctx context.Context, in *Followers, opts ...grpc.CallOption) (*GetFollowers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowers)
	err := c.cc.Invoke(ctx, User_Get_Followers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Get_Following(ctx context.Context, in *Followers, opts ...grpc.CallOption) (*GetFollowing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowing)
	err := c.cc.Invoke(ctx, User_Get_Following_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Search(ctx context.Context, in *Following, opts ...grpc.CallOption) (*GET_UserProfile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GET_UserProfile_Response)
	err := c.cc.Invoke(ctx, User_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Unfollow(ctx context.Context, in *Following, opts ...grpc.CallOption) (*Respond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respond)
	err := c.cc.Invoke(ctx, User_Unfollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	Signup(context.Context, *SignUp) (*Respond, error)
	VErify(context.Context, *Verify) (*Respond, error)
	Signin(context.Context, *SignIn) (*Respond, error)
	LogOut(context.Context, *LogOutDelete) (*Respond, error)
	User_Profile(context.Context, *GET_UserProfile_Request) (*GET_UserProfile_Response, error)
	Update_Profile(context.Context, *PUTUserProfile) (*GET_UserProfile_Response, error)
	Delete_Profile(context.Context, *LogOutDelete) (*Respond, error)
	Follow(context.Context, *Following) (*Respond, error)
	Get_Followers(context.Context, *Followers) (*GetFollowers, error)
	Get_Following(context.Context, *Followers) (*GetFollowing, error)
	Search(context.Context, *Following) (*GET_UserProfile_Response, error)
	Unfollow(context.Context, *Following) (*Respond, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) Signup(context.Context, *SignUp) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedUserServer) VErify(context.Context, *Verify) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VErify not implemented")
}
func (UnimplementedUserServer) Signin(context.Context, *SignIn) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signin not implemented")
}
func (UnimplementedUserServer) LogOut(context.Context, *LogOutDelete) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogOut not implemented")
}
func (UnimplementedUserServer) User_Profile(context.Context, *GET_UserProfile_Request) (*GET_UserProfile_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User_Profile not implemented")
}
func (UnimplementedUserServer) Update_Profile(context.Context, *PUTUserProfile) (*GET_UserProfile_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update_Profile not implemented")
}
func (UnimplementedUserServer) Delete_Profile(context.Context, *LogOutDelete) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete_Profile not implemented")
}
func (UnimplementedUserServer) Follow(context.Context, *Following) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedUserServer) Get_Followers(context.Context, *Followers) (*GetFollowers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get_Followers not implemented")
}
func (UnimplementedUserServer) Get_Following(context.Context, *Followers) (*GetFollowing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get_Following not implemented")
}
func (UnimplementedUserServer) Search(context.Context, *Following) (*GET_UserProfile_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedUserServer) Unfollow(context.Context, *Following) (*Respond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unfollow not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call pancis, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Signup(ctx, req.(*SignUp))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_VErify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Verify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).VErify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_VErify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).VErify(ctx, req.(*Verify))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Signin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Signin(ctx, req.(*SignIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_LogOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogOutDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).LogOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_LogOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).LogOut(ctx, req.(*LogOutDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_User_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GET_UserProfile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).User_Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_User_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).User_Profile(ctx, req.(*GET_UserProfile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Update_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PUTUserProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Update_Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Update_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Update_Profile(ctx, req.(*PUTUserProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Delete_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogOutDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Delete_Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Delete_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Delete_Profile(ctx, req.(*LogOutDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Following)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Follow(ctx, req.(*Following))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Get_Followers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Followers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Get_Followers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Get_Followers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Get_Followers(ctx, req.(*Followers))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Get_Following_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Followers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Get_Following(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Get_Following_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Get_Following(ctx, req.(*Followers))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Following)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Search(ctx, req.(*Following))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Unfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Following)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Unfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Unfollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Unfollow(ctx, req.(*Following))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _User_Signup_Handler,
		},
		{
			MethodName: "VErify",
			Handler:    _User_VErify_Handler,
		},
		{
			MethodName: "Signin",
			Handler:    _User_Signin_Handler,
		},
		{
			MethodName: "LogOut",
			Handler:    _User_LogOut_Handler,
		},
		{
			MethodName: "User_Profile",
			Handler:    _User_User_Profile_Handler,
		},
		{
			MethodName: "Update_Profile",
			Handler:    _User_Update_Profile_Handler,
		},
		{
			MethodName: "Delete_Profile",
			Handler:    _User_Delete_Profile_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _User_Follow_Handler,
		},
		{
			MethodName: "Get_Followers",
			Handler:    _User_Get_Followers_Handler,
		},
		{
			MethodName: "Get_Following",
			Handler:    _User_Get_Following_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _User_Search_Handler,
		},
		{
			MethodName: "Unfollow",
			Handler:    _User_Unfollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/protos/user/user.proto",
}
