// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: internal/protos/user/user.proto

package user17

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SignUp) Reset() {
	*x = SignUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUp) ProtoMessage() {}

func (x *SignUp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUp.ProtoReflect.Descriptor instead.
func (*SignUp) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *SignUp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Verify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Verify) Reset() {
	*x = Verify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Verify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify) ProtoMessage() {}

func (x *Verify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify.ProtoReflect.Descriptor instead.
func (*Verify) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *Verify) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Verify) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SignIn) Reset() {
	*x = SignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn) ProtoMessage() {}

func (x *SignIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn.ProtoReflect.Descriptor instead.
func (*SignIn) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *SignIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LogOutDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *LogOutDelete) Reset() {
	*x = LogOutDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogOutDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutDelete) ProtoMessage() {}

func (x *LogOutDelete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutDelete.ProtoReflect.Descriptor instead.
func (*LogOutDelete) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *LogOutDelete) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Respond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Respond) Reset() {
	*x = Respond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respond) ProtoMessage() {}

func (x *Respond) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respond.ProtoReflect.Descriptor instead.
func (*Respond) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *Respond) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GET_UserProfile_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GET_UserProfile_Request) Reset() {
	*x = GET_UserProfile_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GET_UserProfile_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GET_UserProfile_Request) ProtoMessage() {}

func (x *GET_UserProfile_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GET_UserProfile_Request.ProtoReflect.Descriptor instead.
func (*GET_UserProfile_Request) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *GET_UserProfile_Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Followers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Followers) Reset() {
	*x = Followers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Followers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Followers) ProtoMessage() {}

func (x *Followers) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Followers.ProtoReflect.Descriptor instead.
func (*Followers) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *Followers) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Following struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username     string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	YourUsername string `protobuf:"bytes,2,opt,name=your_username,json=yourUsername,proto3" json:"your_username,omitempty"`
}

func (x *Following) Reset() {
	*x = Following{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Following) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Following) ProtoMessage() {}

func (x *Following) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Following.ProtoReflect.Descriptor instead.
func (*Following) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *Following) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Following) GetYourUsername() string {
	if x != nil {
		return x.YourUsername
	}
	return ""
}

type GetFollowing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Following []*Following `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
}

func (x *GetFollowing) Reset() {
	*x = GetFollowing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFollowing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowing) ProtoMessage() {}

func (x *GetFollowing) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowing.ProtoReflect.Descriptor instead.
func (*GetFollowing) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowing) GetFollowing() []*Following {
	if x != nil {
		return x.Following
	}
	return nil
}

type GetFollowers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Followers []*Following `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
}

func (x *GetFollowers) Reset() {
	*x = GetFollowers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFollowers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowers) ProtoMessage() {}

func (x *GetFollowers) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowers.ProtoReflect.Descriptor instead.
func (*GetFollowers) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetFollowers) GetFollowers() []*Following {
	if x != nil {
		return x.Followers
	}
	return nil
}

type GET_UserProfile_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Followers int32  `protobuf:"varint,3,opt,name=followers,proto3" json:"followers,omitempty"`
	Following int32  `protobuf:"varint,4,opt,name=following,proto3" json:"following,omitempty"`
	Age       int32  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Bio       string `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender    string `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Tweets    int32  `protobuf:"varint,8,opt,name=tweets,proto3" json:"tweets,omitempty"`
	Id        string `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GET_UserProfile_Response) Reset() {
	*x = GET_UserProfile_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GET_UserProfile_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GET_UserProfile_Response) ProtoMessage() {}

func (x *GET_UserProfile_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GET_UserProfile_Response.ProtoReflect.Descriptor instead.
func (*GET_UserProfile_Response) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *GET_UserProfile_Response) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GET_UserProfile_Response) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GET_UserProfile_Response) GetFollowers() int32 {
	if x != nil {
		return x.Followers
	}
	return 0
}

func (x *GET_UserProfile_Response) GetFollowing() int32 {
	if x != nil {
		return x.Following
	}
	return 0
}

func (x *GET_UserProfile_Response) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GET_UserProfile_Response) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GET_UserProfile_Response) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GET_UserProfile_Response) GetTweets() int32 {
	if x != nil {
		return x.Tweets
	}
	return 0
}

func (x *GET_UserProfile_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PUTUserProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age      int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Bio      string `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender   string `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Id       string `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PUTUserProfile) Reset() {
	*x = PUTUserProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_user_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PUTUserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PUTUserProfile) ProtoMessage() {}

func (x *PUTUserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_user_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PUTUserProfile.ProtoReflect.Descriptor instead.
func (*PUTUserProfile) Descriptor() ([]byte, []int) {
	return file_internal_protos_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *PUTUserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PUTUserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PUTUserProfile) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PUTUserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *PUTUserProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PUTUserProfile) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PUTUserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_protos_user_user_proto protoreflect.FileDescriptor

var file_internal_protos_user_user_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x56, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x32, 0x0a, 0x06, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3a, 0x0a,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2b, 0x0a, 0x0d, 0x4c, 0x6f, 0x67,
	0x4f, 0x75, 0x74, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x35, 0x0a, 0x17, 0x47,
	0x45, 0x54, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x27, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x09, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x79, 0x6f, 0x75, 0x72, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x79, 0x6f, 0x75,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x09, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x69, 0x6e, 0x67, 0x22, 0x38, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69,
	0x6e, 0x67, 0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x22, 0xec, 0x01,
	0x0a, 0x18, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xab, 0x01, 0x0a,
	0x0f, 0x50, 0x55, 0x54, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xfc, 0x03, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x07, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x1a, 0x08, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x12, 0x1b, 0x0a, 0x06, 0x56, 0x45, 0x72, 0x69, 0x66, 0x79, 0x12, 0x07, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x1a, 0x08, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x1b, 0x0a,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x07, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e,
	0x1a, 0x08, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x4c, 0x6f,
	0x67, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x4f, 0x75, 0x74, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x1a, 0x08, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x43,
	0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x18,
	0x2e, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x45, 0x54, 0x5f, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x50, 0x55, 0x54, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x19, 0x2e, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x4f, 0x75, 0x74, 0x5f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x1a, 0x08, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x1e,
	0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x0a, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x6e, 0x67, 0x1a, 0x08, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x2a,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x5f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12,
	0x0a, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x1a, 0x0d, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x5f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x0a, 0x2e, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x1a, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x0a, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x1a, 0x19, 0x2e, 0x47,
	0x45, 0x54, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x08, 0x55, 0x6e, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x12, 0x0a, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x1a,
	0x08, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x31, 0x37, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_user_user_proto_rawDescOnce sync.Once
	file_internal_protos_user_user_proto_rawDescData = file_internal_protos_user_user_proto_rawDesc
)

func file_internal_protos_user_user_proto_rawDescGZIP() []byte {
	file_internal_protos_user_user_proto_rawDescOnce.Do(func() {
		file_internal_protos_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_user_user_proto_rawDescData)
	})
	return file_internal_protos_user_user_proto_rawDescData
}

var file_internal_protos_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_protos_user_user_proto_goTypes = []any{
	(*SignUp)(nil),                   // 0: SignUp
	(*Verify)(nil),                   // 1: Verify
	(*SignIn)(nil),                   // 2: SignIn
	(*LogOutDelete)(nil),             // 3: LogOut_delete
	(*Respond)(nil),                  // 4: Respond
	(*GET_UserProfile_Request)(nil),  // 5: GET_UserProfile_Request
	(*Followers)(nil),                // 6: Followers
	(*Following)(nil),                // 7: Following
	(*GetFollowing)(nil),             // 8: GetFollowing
	(*GetFollowers)(nil),             // 9: GetFollowers
	(*GET_UserProfile_Response)(nil), // 10: GET_UserProfile_Response
	(*PUTUserProfile)(nil),           // 11: PUT_userProfile
}
var file_internal_protos_user_user_proto_depIdxs = []int32{
	7,  // 0: GetFollowing.following:type_name -> Following
	7,  // 1: GetFollowers.followers:type_name -> Following
	0,  // 2: User.Signup:input_type -> SignUp
	1,  // 3: User.VErify:input_type -> Verify
	2,  // 4: User.Signin:input_type -> SignIn
	3,  // 5: User.LogOut:input_type -> LogOut_delete
	5,  // 6: User.User_Profile:input_type -> GET_UserProfile_Request
	11, // 7: User.Update_Profile:input_type -> PUT_userProfile
	3,  // 8: User.Delete_Profile:input_type -> LogOut_delete
	7,  // 9: User.Follow:input_type -> Following
	6,  // 10: User.Get_Followers:input_type -> Followers
	6,  // 11: User.Get_Following:input_type -> Followers
	7,  // 12: User.Search:input_type -> Following
	7,  // 13: User.Unfollow:input_type -> Following
	4,  // 14: User.Signup:output_type -> Respond
	4,  // 15: User.VErify:output_type -> Respond
	4,  // 16: User.Signin:output_type -> Respond
	4,  // 17: User.LogOut:output_type -> Respond
	10, // 18: User.User_Profile:output_type -> GET_UserProfile_Response
	10, // 19: User.Update_Profile:output_type -> GET_UserProfile_Response
	4,  // 20: User.Delete_Profile:output_type -> Respond
	4,  // 21: User.Follow:output_type -> Respond
	9,  // 22: User.Get_Followers:output_type -> GetFollowers
	8,  // 23: User.Get_Following:output_type -> GetFollowing
	10, // 24: User.Search:output_type -> GET_UserProfile_Response
	4,  // 25: User.Unfollow:output_type -> Respond
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protos_user_user_proto_init() }
func file_internal_protos_user_user_proto_init() {
	if File_internal_protos_user_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_user_user_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SignUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Verify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LogOutDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Respond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GET_UserProfile_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Followers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Following); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetFollowing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetFollowers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GET_UserProfile_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_user_user_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*PUTUserProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_user_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_user_user_proto_goTypes,
		DependencyIndexes: file_internal_protos_user_user_proto_depIdxs,
		MessageInfos:      file_internal_protos_user_user_proto_msgTypes,
	}.Build()
	File_internal_protos_user_user_proto = out.File
	file_internal_protos_user_user_proto_rawDesc = nil
	file_internal_protos_user_user_proto_goTypes = nil
	file_internal_protos_user_user_proto_depIdxs = nil
}
