// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: internal/protos/like_retweet/like_retweet.proto

package like_retweet17

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LikeAmount    int32 `protobuf:"varint,1,opt,name=like_amount,json=likeAmount,proto3" json:"like_amount,omitempty"`
	RetweetAmount int32 `protobuf:"varint,2,opt,name=retweet_amount,json=retweetAmount,proto3" json:"retweet_amount,omitempty"`
	Comments      int32 `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetLikeAmount() int32 {
	if x != nil {
		return x.LikeAmount
	}
	return 0
}

func (x *Info) GetRetweetAmount() int32 {
	if x != nil {
		return x.RetweetAmount
	}
	return 0
}

func (x *Info) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type Like_Comment_Retweet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TweetId     int32  `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	TweetedUser string `protobuf:"bytes,2,opt,name=tweeted_user,json=tweetedUser,proto3" json:"tweeted_user,omitempty"`
	Username    string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Comment     string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Like        bool   `protobuf:"varint,5,opt,name=like,proto3" json:"like,omitempty"`
	Retweet     bool   `protobuf:"varint,6,opt,name=retweet,proto3" json:"retweet,omitempty"`
}

func (x *Like_Comment_Retweet) Reset() {
	*x = Like_Comment_Retweet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Like_Comment_Retweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like_Comment_Retweet) ProtoMessage() {}

func (x *Like_Comment_Retweet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like_Comment_Retweet.ProtoReflect.Descriptor instead.
func (*Like_Comment_Retweet) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{1}
}

func (x *Like_Comment_Retweet) GetTweetId() int32 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

func (x *Like_Comment_Retweet) GetTweetedUser() string {
	if x != nil {
		return x.TweetedUser
	}
	return ""
}

func (x *Like_Comment_Retweet) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Like_Comment_Retweet) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Like_Comment_Retweet) GetLike() bool {
	if x != nil {
		return x.Like
	}
	return false
}

func (x *Like_Comment_Retweet) GetRetweet() bool {
	if x != nil {
		return x.Retweet
	}
	return false
}

type Liked_CommentedUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TweetId     int32  `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	TweetedUser string `protobuf:"bytes,2,opt,name=tweeted_user,json=tweetedUser,proto3" json:"tweeted_user,omitempty"`
}

func (x *Liked_CommentedUsers) Reset() {
	*x = Liked_CommentedUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Liked_CommentedUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Liked_CommentedUsers) ProtoMessage() {}

func (x *Liked_CommentedUsers) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Liked_CommentedUsers.ProtoReflect.Descriptor instead.
func (*Liked_CommentedUsers) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{2}
}

func (x *Liked_CommentedUsers) GetTweetId() int32 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

func (x *Liked_CommentedUsers) GetTweetedUser() string {
	if x != nil {
		return x.TweetedUser
	}
	return ""
}

type UsersLiked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *UsersLiked) Reset() {
	*x = UsersLiked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersLiked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersLiked) ProtoMessage() {}

func (x *UsersLiked) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersLiked.ProtoReflect.Descriptor instead.
func (*UsersLiked) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{3}
}

func (x *UsersLiked) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LikedUser_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*UsersLiked `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *LikedUser_Response) Reset() {
	*x = LikedUser_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikedUser_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikedUser_Response) ProtoMessage() {}

func (x *LikedUser_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikedUser_Response.ProtoReflect.Descriptor instead.
func (*LikedUser_Response) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{4}
}

func (x *LikedUser_Response) GetUsers() []*UsersLiked {
	if x != nil {
		return x.Users
	}
	return nil
}

type CommentedUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Comment  string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *CommentedUsers) Reset() {
	*x = CommentedUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentedUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentedUsers) ProtoMessage() {}

func (x *CommentedUsers) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentedUsers.ProtoReflect.Descriptor instead.
func (*CommentedUsers) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{5}
}

func (x *CommentedUsers) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentedUsers) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CommentedUsers_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User []*CommentedUsers `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
}

func (x *CommentedUsers_Response) Reset() {
	*x = CommentedUsers_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentedUsers_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentedUsers_Response) ProtoMessage() {}

func (x *CommentedUsers_Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentedUsers_Response.ProtoReflect.Descriptor instead.
func (*CommentedUsers_Response) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{6}
}

func (x *CommentedUsers_Response) GetUser() []*CommentedUsers {
	if x != nil {
		return x.User
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protos_like_retweet_like_retweet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP(), []int{7}
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_protos_like_retweet_like_retweet_proto protoreflect.FileDescriptor

var file_internal_protos_like_retweet_like_retweet_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2f, 0x6c,
	0x69, 0x6b, 0x65, 0x5f, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6a, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x6b,
	0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6c, 0x69, 0x6b, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xb8, 0x01,
	0x0a, 0x14, 0x4c, 0x69, 0x6b, 0x65, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x52,
	0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x77, 0x65, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x77, 0x65, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x77, 0x65, 0x65, 0x74, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69,
	0x6b, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x15, 0x4c, 0x69, 0x6b, 0x65,
	0x64, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x77, 0x65, 0x65, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x74, 0x77, 0x65, 0x65, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x22,
	0x29, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x13, 0x4c, 0x69,
	0x6b, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x47, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x40,
	0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x22, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0xac, 0x02, 0x0a, 0x14, 0x4c, 0x69, 0x6b, 0x65, 0x5f, 0x52, 0x65,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a,
	0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x4c,
	0x69, 0x6b, 0x65, 0x64, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x1a, 0x05, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x03, 0x4c,
	0x52, 0x43, 0x12, 0x15, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x52, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x1a, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x3a, 0x0a, 0x0a, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x16, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x14, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x64,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x16, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x19, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x5f, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x14, 0x2e,
	0x4c, 0x69, 0x6b, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x72, 0x65,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x31, 0x37, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_protos_like_retweet_like_retweet_proto_rawDescOnce sync.Once
	file_internal_protos_like_retweet_like_retweet_proto_rawDescData = file_internal_protos_like_retweet_like_retweet_proto_rawDesc
)

func file_internal_protos_like_retweet_like_retweet_proto_rawDescGZIP() []byte {
	file_internal_protos_like_retweet_like_retweet_proto_rawDescOnce.Do(func() {
		file_internal_protos_like_retweet_like_retweet_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protos_like_retweet_like_retweet_proto_rawDescData)
	})
	return file_internal_protos_like_retweet_like_retweet_proto_rawDescData
}

var file_internal_protos_like_retweet_like_retweet_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_protos_like_retweet_like_retweet_proto_goTypes = []any{
	(*Info)(nil),                    // 0: Info
	(*Like_Comment_Retweet)(nil),    // 1: Like_Comment_Retweet
	(*Liked_CommentedUsers)(nil),    // 2: Liked_Commented_users
	(*UsersLiked)(nil),              // 3: users_liked
	(*LikedUser_Response)(nil),      // 4: Liked_user_Response
	(*CommentedUsers)(nil),          // 5: Commented_users
	(*CommentedUsers_Response)(nil), // 6: Commented_users_Response
	(*Status)(nil),                  // 7: Status
}
var file_internal_protos_like_retweet_like_retweet_proto_depIdxs = []int32{
	3, // 0: Liked_user_Response.users:type_name -> users_liked
	5, // 1: Commented_users_Response.user:type_name -> Commented_users
	2, // 2: Like_Retweet_Comment.Information:input_type -> Liked_Commented_users
	1, // 3: Like_Retweet_Comment.LRC:input_type -> Like_Comment_Retweet
	2, // 4: Like_Retweet_Comment.LikedUsers:input_type -> Liked_Commented_users
	2, // 5: Like_Retweet_Comment.CommentedUsers:input_type -> Liked_Commented_users
	2, // 6: Like_Retweet_Comment.RetweetedUsers:input_type -> Liked_Commented_users
	0, // 7: Like_Retweet_Comment.Information:output_type -> Info
	7, // 8: Like_Retweet_Comment.LRC:output_type -> Status
	4, // 9: Like_Retweet_Comment.LikedUsers:output_type -> Liked_user_Response
	6, // 10: Like_Retweet_Comment.CommentedUsers:output_type -> Commented_users_Response
	4, // 11: Like_Retweet_Comment.RetweetedUsers:output_type -> Liked_user_Response
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protos_like_retweet_like_retweet_proto_init() }
func file_internal_protos_like_retweet_like_retweet_proto_init() {
	if File_internal_protos_like_retweet_like_retweet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Like_Comment_Retweet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Liked_CommentedUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UsersLiked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LikedUser_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CommentedUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CommentedUsers_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protos_like_retweet_like_retweet_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protos_like_retweet_like_retweet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protos_like_retweet_like_retweet_proto_goTypes,
		DependencyIndexes: file_internal_protos_like_retweet_like_retweet_proto_depIdxs,
		MessageInfos:      file_internal_protos_like_retweet_like_retweet_proto_msgTypes,
	}.Build()
	File_internal_protos_like_retweet_like_retweet_proto = out.File
	file_internal_protos_like_retweet_like_retweet_proto_rawDesc = nil
	file_internal_protos_like_retweet_like_retweet_proto_goTypes = nil
	file_internal_protos_like_retweet_like_retweet_proto_depIdxs = nil
}
