// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/protos/like_retweet/like_retweet.proto

package like_retweet17

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Like_Retweet_Comment_Information_FullMethodName    = "/Like_Retweet_Comment/Information"
	Like_Retweet_Comment_LRC_FullMethodName            = "/Like_Retweet_Comment/LRC"
	Like_Retweet_Comment_LikedUsers_FullMethodName     = "/Like_Retweet_Comment/LikedUsers"
	Like_Retweet_Comment_CommentedUsers_FullMethodName = "/Like_Retweet_Comment/CommentedUsers"
	Like_Retweet_Comment_RetweetedUsers_FullMethodName = "/Like_Retweet_Comment/RetweetedUsers"
)

// Like_Retweet_CommentClient is the client API for Like_Retweet_Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Like_Retweet_CommentClient interface {
	Information(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*Info, error)
	LRC(ctx context.Context, in *Like_Comment_Retweet, opts ...grpc.CallOption) (*Status, error)
	LikedUsers(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*LikedUser_Response, error)
	CommentedUsers(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*CommentedUsers_Response, error)
	RetweetedUsers(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*LikedUser_Response, error)
}

type like_Retweet_CommentClient struct {
	cc grpc.ClientConnInterface
}

func NewLike_Retweet_CommentClient(cc grpc.ClientConnInterface) Like_Retweet_CommentClient {
	return &like_Retweet_CommentClient{cc}
}

func (c *like_Retweet_CommentClient) Information(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*Info, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Info)
	err := c.cc.Invoke(ctx, Like_Retweet_Comment_Information_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *like_Retweet_CommentClient) LRC(ctx context.Context, in *Like_Comment_Retweet, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Like_Retweet_Comment_LRC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *like_Retweet_CommentClient) LikedUsers(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*LikedUser_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikedUser_Response)
	err := c.cc.Invoke(ctx, Like_Retweet_Comment_LikedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *like_Retweet_CommentClient) CommentedUsers(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*CommentedUsers_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentedUsers_Response)
	err := c.cc.Invoke(ctx, Like_Retweet_Comment_CommentedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *like_Retweet_CommentClient) RetweetedUsers(ctx context.Context, in *Liked_CommentedUsers, opts ...grpc.CallOption) (*LikedUser_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikedUser_Response)
	err := c.cc.Invoke(ctx, Like_Retweet_Comment_RetweetedUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Like_Retweet_CommentServer is the server API for Like_Retweet_Comment service.
// All implementations must embed UnimplementedLike_Retweet_CommentServer
// for forward compatibility.
type Like_Retweet_CommentServer interface {
	Information(context.Context, *Liked_CommentedUsers) (*Info, error)
	LRC(context.Context, *Like_Comment_Retweet) (*Status, error)
	LikedUsers(context.Context, *Liked_CommentedUsers) (*LikedUser_Response, error)
	CommentedUsers(context.Context, *Liked_CommentedUsers) (*CommentedUsers_Response, error)
	RetweetedUsers(context.Context, *Liked_CommentedUsers) (*LikedUser_Response, error)
	mustEmbedUnimplementedLike_Retweet_CommentServer()
}

// UnimplementedLike_Retweet_CommentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLike_Retweet_CommentServer struct{}

func (UnimplementedLike_Retweet_CommentServer) Information(context.Context, *Liked_CommentedUsers) (*Info, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Information not implemented")
}
func (UnimplementedLike_Retweet_CommentServer) LRC(context.Context, *Like_Comment_Retweet) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LRC not implemented")
}
func (UnimplementedLike_Retweet_CommentServer) LikedUsers(context.Context, *Liked_CommentedUsers) (*LikedUser_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikedUsers not implemented")
}
func (UnimplementedLike_Retweet_CommentServer) CommentedUsers(context.Context, *Liked_CommentedUsers) (*CommentedUsers_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentedUsers not implemented")
}
func (UnimplementedLike_Retweet_CommentServer) RetweetedUsers(context.Context, *Liked_CommentedUsers) (*LikedUser_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetweetedUsers not implemented")
}
func (UnimplementedLike_Retweet_CommentServer) mustEmbedUnimplementedLike_Retweet_CommentServer() {}
func (UnimplementedLike_Retweet_CommentServer) testEmbeddedByValue()                              {}

// UnsafeLike_Retweet_CommentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Like_Retweet_CommentServer will
// result in compilation errors.
type UnsafeLike_Retweet_CommentServer interface {
	mustEmbedUnimplementedLike_Retweet_CommentServer()
}

func RegisterLike_Retweet_CommentServer(s grpc.ServiceRegistrar, srv Like_Retweet_CommentServer) {
	// If the following call pancis, it indicates UnimplementedLike_Retweet_CommentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Like_Retweet_Comment_ServiceDesc, srv)
}

func _Like_Retweet_Comment_Information_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Liked_CommentedUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Like_Retweet_CommentServer).Information(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_Retweet_Comment_Information_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Like_Retweet_CommentServer).Information(ctx, req.(*Liked_CommentedUsers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_Retweet_Comment_LRC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Like_Comment_Retweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Like_Retweet_CommentServer).LRC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_Retweet_Comment_LRC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Like_Retweet_CommentServer).LRC(ctx, req.(*Like_Comment_Retweet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_Retweet_Comment_LikedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Liked_CommentedUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Like_Retweet_CommentServer).LikedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_Retweet_Comment_LikedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Like_Retweet_CommentServer).LikedUsers(ctx, req.(*Liked_CommentedUsers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_Retweet_Comment_CommentedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Liked_CommentedUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Like_Retweet_CommentServer).CommentedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_Retweet_Comment_CommentedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Like_Retweet_CommentServer).CommentedUsers(ctx, req.(*Liked_CommentedUsers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_Retweet_Comment_RetweetedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Liked_CommentedUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Like_Retweet_CommentServer).RetweetedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_Retweet_Comment_RetweetedUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Like_Retweet_CommentServer).RetweetedUsers(ctx, req.(*Liked_CommentedUsers))
	}
	return interceptor(ctx, in, info, handler)
}

// Like_Retweet_Comment_ServiceDesc is the grpc.ServiceDesc for Like_Retweet_Comment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Like_Retweet_Comment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Like_Retweet_Comment",
	HandlerType: (*Like_Retweet_CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Information",
			Handler:    _Like_Retweet_Comment_Information_Handler,
		},
		{
			MethodName: "LRC",
			Handler:    _Like_Retweet_Comment_LRC_Handler,
		},
		{
			MethodName: "LikedUsers",
			Handler:    _Like_Retweet_Comment_LikedUsers_Handler,
		},
		{
			MethodName: "CommentedUsers",
			Handler:    _Like_Retweet_Comment_CommentedUsers_Handler,
		},
		{
			MethodName: "RetweetedUsers",
			Handler:    _Like_Retweet_Comment_RetweetedUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/protos/like_retweet/like_retweet.proto",
}
