name: Build, Push and Deploy Docker Image

on:
  push:
    branches: [ "unknown17" ]
  pull_request:
    branches: [ "unknown17" ]

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 54.93.169.32
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Ensure we're in the correct directory
            if [ ! -d "twitter/mini/.git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/unknownn17/X-mini_twiiter- twitter/mini
            fi
            cd twitter/mini
            
            # Check if it's a valid git repository
            if [ ! -d ".git" ]; then
              echo "Not a valid git repository. Exiting."
              exit 1
            fi
            
            # Pull the latest code
            git pull origin unknown17
            
            # Ensure Docker is started and running
            sudo systemctl start docker
            sudo systemctl enable docker
            
            # Verify Docker is running
            sudo docker --version
            sudo docker ps
            
            # Check if docker-compose.yml exists
            if [ ! -f "docker-compose.yml" ]; then
              echo "docker-compose.yml not found. Exiting."
              exit 1
            fi
            
            # Run Docker Compose commands
            sudo docker-compose down
            sudo docker-compose up --build -d
          timeout: 200s
